name: weather_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  dio: ^5.4.0
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.9
  tuple: ^2.0.2
  geolocator: ^11.0.0
  google_fonts: ^6.1.0
  geocoding: ^2.1.1
  intl: ^0.19.0
  scrollable_positioned_list: ^0.3.8
  shimmer: ^3.0.0
  flutter_native_splash: ^2.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/icons/