name: Release Build

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting workflow for releasing build"
      - uses: actions/checkout@v4

      - name: Setup Flutter & build APK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
          channel: 'stable'
      - run: flutter --version
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk

      - name: Upload apk build as an Artifact
        uses: actions/upload-artifact@v1
        with:
          name: staging-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
